//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_UltraschallVR : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean AnyTriggerPressed
        {
            get
            {
                return SteamVR_Actions.ultraschallVR_AnyTriggerPressed;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.ultraschallVR_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchpadPosition
        {
            get
            {
                return SteamVR_Actions.ultraschallVR_TouchpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadPressed
        {
            get
            {
                return SteamVR_Actions.ultraschallVR_TouchpadPressed;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTriggerPressed
        {
            get
            {
                return SteamVR_Actions.ultraschallVR_LeftTriggerPressed;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTriggerPressed
        {
            get
            {
                return SteamVR_Actions.ultraschallVR_RightTriggerPressed;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.ultraschallVR_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightAPressed
        {
            get
            {
                return SteamVR_Actions.ultraschallVR_RightAPressed;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.ultraschallVR_Haptic;
            }
        }
    }
}
